- hosts: localhost
  user: super_user
  become: yes
  vars_files:
    - [ "vars.yml" ]
  roles:
    - role: packages
      vars:
        package_name: DNS
        packages:
            - bind9
            - bind9utils
            - bind9-doc
    - role: packages
      vars:
        package_name: rsync
        packages:
            - rsync
    - role: packages
      vars:
        package_name: SSH
        packages:
            - ssh
    - role: packages
      vars:
        package_name: desktop
        packages:
            - chromium-browser
            - evolution
    - role: packages
      when: ansible_facts['os_family'] == 'Debian'
      vars:
        package_name: APT
        packages:
            - software-properties-common
            - apt-transport-https
    - role: repo_apt_add
      vars:
        repo_key_url: https://packages.microsoft.com/keys/microsoft.asc
        repo_name: vscode
        repo: https://packages.microsoft.com/repos/vscode
    - role: packages
      vars:
        package_name: Java
        packages:
          - default-jre
    - role: packages
      vars:
        package_name: Music
        packages:
            # - musicbox
            # - tauon
    - role: packages
      vars:
        package_name: developer
        packages:
            - code
            # - sudo snap install --classic eclipse